# Generated by Django 4.2.8 on 2023-12-18 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirData',
            fields=[
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('point', models.CharField(blank=True, max_length=255, null=True)),
                ('aqi', models.IntegerField(blank=True, null=True)),
                ('quality', models.CharField(blank=True, max_length=255, null=True)),
                ('pm25', models.FloatField(blank=True, null=True)),
                ('pm10', models.FloatField(blank=True, null=True)),
                ('co', models.FloatField(blank=True, null=True)),
                ('no2', models.FloatField(blank=True, null=True)),
                ('so2', models.FloatField(blank=True, null=True)),
                ('o3', models.FloatField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('update_slot', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_flag', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': '空气质量数据',
                'db_table': 'air_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PubName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubname', models.CharField(max_length=255, unique=True, verbose_name='名称')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.pubname'),
        ),
    ]
