# Generated by Django 4.2.8 on 2023-12-18 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_airdata_pubname_book_pub'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendUserinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(help_text='自建签名', max_length=255, verbose_name='用户签名')),
                ('nickname', models.CharField(help_text='自建昵称', max_length=255, verbose_name='昵称')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.userinfo')),
            ],
        ),
    ]
